name: main_workflow

on:
  push:
    branches:
      - github_action_readme

permissions:
  contents: write

jobs:
  linter-execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Linter execution
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true

  test-execution:
    runs-on: ubuntu-latest
    needs: 
      - linter-execution
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Jest
        run: npm install jest --legacy-peer-deps
      - name: Run Jest Test
        run: npm run test

  modify-readme-job:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test-execution
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Modify Readme with Memes
        uses: ./.github/actions/memes
        with:
          frase_positiva: "Los tests han funcionado y lo sabes"
          frase_negativa: "Los tests han fallado y lo sabes"
          resultado_test: ${{ needs.test-execution.result }}
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: "Elu Mancebo"
          author_email: "emango0298@gmail.com"
          message: "Actualizado el meme del readme"
          push: true
          token: ${{ secrets.TOKEN }}
